# Auto-generated from the user-provided "cryptid-cluebooks.pdf" (transcribed)
# Source: Osprey Games cluebooks included with Cryptid.
CLUEBOOKS = {
    "A_Red": [
        "within two spaces of bear territory",
        "on water or mountains",
        "within one space of mountain",
        "not on water or mountains",
        "not on forest or water",
        "not within two spaces of bear territory",
        "not on desert or water",
        "not on forest or swamp",
        "on swamp or mountain",
        "on forest or water",
        "not within two spaces of a standing stone",
        "within one space of forest",
        "within three spaces of a white structure",
        "not within one space of water",
        "not on forest or mountain",
        "not within one space of either animal territory",
        "within two spaces of cougar territory",
        "within three spaces of a blue structure",
        "within one space of swamp",
        "within three spaces of a green structure",
        "within two spaces of an abandoned shack",
        "not on desert or water",
        "not within two spaces of cougar territory",
        "not within two spaces of an abandoned shack",
        "on desert or water",
        "within one space of water",
        "on desert or water",
        "within one space of swamp",
        "on forest or mountain",
        "within one space of forest",
        "within three spaces of a black structure",
        "not on forest or swamp",
        "within three spaces of a green structure",
        "on desert or swamp",
        "not on swamp or mountain",
        "within three spaces of a blue structure",
        "not within one space of mountain",
        "not on forest or desert",
        "not within two spaces of bear territory",
        "not on swamp or mountain",
        "not within two spaces of an abandoned shack",
        "within three spaces of a white structure",
        "not within one space of desert",
        "on water or swamp",
        "not on desert or mountain",
        "within two spaces of a standing stone",
        "not on water or swamp",
        "within two spaces of cougar territory",
        "not within one space of either animal territory",
        "within one space of either animal territory",
        "not on desert or swamp",
        "within one space of mountain",
        "not within three spaces of a white structure",
        "on forest or swamp",
        "within two spaces of a standing stone",
        "on desert or mountain",
        "on forest or desert",
        "not within one space of swamp",
        "not within three spaces of a black structure",
        "not on water or swamp",
        "on desert or swamp",
        "not within three spaces of a green structure",
        "not on desert or mountain",
        "not on forest or mountain",
        "within one space of desert",
        "on desert or mountain",
        "not within one space of desert",
        "on forest or swamp",
        "within one space of desert",
        "not within two spaces of a standing stone",
        "not on water or mountains",
        "on swamp or mountain",
        "not on forest or water",
        "not within one space of forest",
        "not on forest or desert",
        "not within three spaces of a white structure",
        "on forest or desert",
        "not within one space of forest",
        "not within one space of mountain",
        "on forest or mountain",
        "not within three spaces of a blue structure",
        "not on desert or swamp",
        "within two spaces of an abandoned shack",
        "within one space of either animal territory",
        "within one space of water",
        "not within one space of water",
        "not within three spaces of a blue structure",
        "on forest or water",
        "not within one space of swamp",
        "not within three spaces of a black structure",
        "within two spaces of bear territory",
        "on water or mountains",
        "within three spaces of a black structure",
        "not within two spaces of cougar territory",
        "on water or swamp",
        "not within three spaces of a green structure",
    ],
    "B_Green": [
        "on desert or swamp",
        "within two spaces of cougar territory",
        "within three spaces of a blue structure",
        "not on forest or swamp",
        "within three spaces of a green structure",
        "within one space of desert",
        "not on desert or swamp",
        "on forest or swamp",
        "not on water or swamp",
        "not within three spaces of a black structure",
        "within two spaces of an abandoned shack",
        "not within one space of desert",
        "on forest or water",
        "not within three spaces of a white structure",
        "not within one space of either animal territory",
        "within two spaces of bear territory",
        "within one space of water",
        "not on swamp or mountain",
        "within one space of mountain",
        "not within three spaces of a black structure",
        "not within one space of swamp",
        "within three spaces of a black structure",
        "not within three spaces of a green structure",
        "not on forest or desert",
        "within one space of swamp",
        "not on forest or mountain",
        "not within two spaces of bear territory",
        "on forest or mountain",
        "on swamp or mountain",
        "not within two spaces of cougar territory",
        "not within two spaces of a standing stone",
        "on water or swamp",
        "on desert or water",
        "within three spaces of a blue structure",
        "within two spaces of a standing stone",
        "on water or mountains",
        "not on forest or swamp",
        "not on water or swamp",
        "not within two spaces of an abandoned shack",
        "not within one space of mountain",
        "not on desert or mountain",
        "within one space of forest",
        "within two spaces of bear territory",
        "not within one space of either animal territory",
        "within three spaces of a green structure",
        "within one space of either animal territory",
        "on desert or mountain",
        "not within two spaces of bear territory",
        "within one space of mountain",
        "not on desert or water",
        "not within one space of forest",
        "not within two spaces of an abandoned shack",
        "within two spaces of an abandoned shack",
        "within one space of swamp",
        "not within one space of desert",
        "not on desert or swamp",
        "not on desert or mountain",
        "within three spaces of a black structure",
        "not within one space of forest",
        "not within three spaces of a blue structure",
        "within one space of water",
        "on forest or water",
        "not on desert or water",
        "within three spaces of a white structure",
        "within two spaces of a standing stone",
        "within two spaces of cougar territory",
        "within one space of either animal territory",
        "not within one space of water",
        "not within three spaces of a blue structure",
        "not on forest or desert",
        "within one space of forest",
        "not on forest or mountain",
        "on desert or swamp",
        "on water or mountains",
        "not on swamp or mountain",
        "on forest or desert",
        "on desert or water",
        "not within three spaces of a white structure",
        "within three spaces of a white structure",
        "within one space of desert",
        "not within one space of mountain",
        "on forest or desert",
        "on forest or mountain",
        "not on water or mountains",
        "not within one space of water",
        "on water or swamp",
        "not on forest or water",
        "not within two spaces of cougar territory",
        "on desert or mountain",
        "on forest or swamp",
        "not on water or mountains",
        "on swamp or mountain",
        "not on forest or water",
        "not within two spaces of a standing stone",
        "not within three spaces of a green structure",
        "not within one space of swamp",
    ],
    "C_Blue": [
        "within three spaces of a blue structure",
        "within one space of water",
        "not on water or mountains",
        "on forest or swamp",
        "not on desert or water",
        "within three spaces of a blue structure",
        "not within one space of desert",
        "not on forest or swamp",
        "not on forest or water",
        "not within two spaces of a standing stone",
        "within three spaces of a green structure",
        "within two spaces of a standing stone",
        "on forest or water",
        "not within three spaces of a black structure",
        "not on forest or swamp",
        "not within two spaces of a standing stone",
        "not within one space of mountain",
        "on desert or mountain",
        "not on desert or swamp",
        "on desert or swamp",
        "on forest or desert",
        "not on forest or desert",
        "within one space of mountain",
        "not within one space of swamp",
        "within three spaces of a black structure",
        "not within three spaces of a blue structure",
        "within one space of forest",
        "within three spaces of a white structure",
        "within one space of either animal territory",
        "not within three spaces of a white structure",
        "on water or swamp",
        "on swamp or mountain",
        "not on desert or swamp",
        "not within three spaces of a green structure",
        "within three spaces of a green structure",
        "within one space of forest",
        "not on desert or water",
        "not within two spaces of bear territory",
        "on water or mountains",
        "within three spaces of a white structure",
        "on water or mountains",
        "not within three spaces of a blue structure",
        "on forest or mountain",
        "within two spaces of bear territory",
        "not within one space of swamp",
        "not within one space of forest",
        "within three spaces of a black structure",
        "on desert or swamp",
        "within two spaces of cougar territory",
        "within two spaces of cougar territory",
        "not on swamp or mountain",
        "not within two spaces of bear territory",
        "within one space of either animal territory",
        "within two spaces of bear territory",
        "not on forest or mountain",
        "not on water or swamp",
        "not on water or mountains",
        "not within one space of either animal territory",
        "not on forest or water",
        "not on desert or mountain",
        "not on forest or desert",
        "not within one space of water",
        "within two spaces of a standing stone",
        "not on swamp or mountain",
        "within two spaces of an abandoned shack",
        "not on water or swamp",
        "not within one space of mountain",
        "within one space of desert",
        "not within two spaces of cougar territory",
        "on water or swamp",
        "within two spaces of an abandoned shack",
        "not within three spaces of a green structure",
        "within one space of water",
        "on forest or desert",
        "not within one space of either animal territory",
        "not within one space of forest",
        "on forest or mountain",
        "not within two spaces of an abandoned shack",
        "not on forest or mountain",
        "on desert or mountain",
        "within one space of desert",
        "not within one space of water",
        "not within two spaces of an abandoned shack",
        "within one space of swamp",
        "on desert or water",
        "not within two spaces of cougar territory",
        "on forest or water",
        "not within three spaces of a black structure",
        "on forest or swamp",
        "not on desert or mountain",
        "not within three spaces of a white structure",
        "on desert or water",
        "within one space of mountain",
        "within one space of swamp",
        "not within one space of desert",
        "on swamp or mountain",
    ],
    "D_Orange": [
        "not on swamp or mountain",
        "within two spaces of bear territory",
        "not within two spaces of cougar territory",
        "within one space of mountain",
        "not on desert or mountain",
        "not within three spaces of a black structure",
        "on forest or desert",
        "not on forest or water",
        "not within two spaces of bear territory",
        "not within one space of water",
        "on desert or water",
        "not on desert or swamp",
        "within two spaces of bear territory",
        "within one space of swamp",
        "within three spaces of a green structure",
        "not within two spaces of a standing stone",
        "within two spaces of an abandoned shack",
        "not within two spaces of a standing stone",
        "on forest or mountain",
        "within one space of water",
        "not within one space of desert",
        "within three spaces of a black structure",
        "not on water or mountains",
        "on water or mountains",
        "on swamp or mountain",
        "within one space of desert",
        "on desert or swamp",
        "not on forest or desert",
        "within three spaces of a black structure",
        "within one space of forest",
        "not on swamp or mountain",
        "not within three spaces of a blue structure",
        "not on desert or water",
        "on desert or mountain",
        "on water or swamp",
        "within three spaces of a white structure",
        "not on water or mountains",
        "not within two spaces of an abandoned shack",
        "on forest or swamp",
        "on swamp or mountain",
        "not on water or swamp",
        "within one space of swamp",
        "within three spaces of a blue structure",
        "not within one space of mountain",
        "within two spaces of a standing stone",
        "within one space of desert",
        "within one space of mountain",
        "not within three spaces of a white structure",
        "within two spaces of a standing stone",
        "on forest or water",
        "on desert or swamp",
        "within two spaces of an abandoned shack",
        "on water or mountains",
        "not on forest or mountain",
        "not within three spaces of a blue structure",
        "within three spaces of a white structure",
        "not on water or swamp",
        "within one space of either animal territory",
        "on forest or swamp",
        "not on forest or swamp",
        "not within one space of water",
        "not within one space of either animal territory",
        "within two spaces of cougar territory",
        "not within two spaces of bear territory",
        "not on forest or water",
        "not within three spaces of a black structure",
        "not within one space of desert",
        "not within two spaces of an abandoned shack",
        "on water or swamp",
        "not within three spaces of a green structure",
        "not on forest or swamp",
        "within two spaces of cougar territory",
        "within three spaces of a blue structure",
        "on forest or mountain",
        "not on forest or mountain",
        "not on desert or water",
        "within one space of forest",
        "on desert or water",
        "not within one space of forest",
        "not on forest or desert",
        "on desert or mountain",
        "not within one space of either animal territory",
        "within one space of either animal territory",
        "within one space of water",
        "within three spaces of a green structure",
        "on forest or water",
        "not within one space of swamp",
        "not within one space of mountain",
        "not within three spaces of a green structure",
        "not within three spaces of a white structure",
        "on forest or desert",
        "not within one space of forest",
        "not on desert or mountain",
        "not within one space of swamp",
        "not within two spaces of cougar territory",
        "not on desert or swamp",
    ],
    "E_Purple": [
        "on forest or swamp",
        "within one space of forest",
        "not within one space of either animal territory",
        "not on forest or mountain",
        "not on forest or swamp",
        "not within three spaces of a blue structure",
        "within three spaces of a black structure",
        "on desert or water",
        "within three spaces of a green structure",
        "not within two spaces of an abandoned shack",
        "within one space of desert",
        "not within two spaces of bear territory",
        "within one space of either animal territory",
        "not within one space of mountain",
        "not within one space of either animal territory",
        "within three spaces of a white structure",
        "within one space of water",
        "not within one space of desert",
        "within three spaces of a black structure",
        "not on forest or desert",
        "within two spaces of cougar territory",
        "within one space of water",
        "within two spaces of cougar territory",
        "not on desert or swamp",
        "not on forest or desert",
        "on forest or mountain",
        "on forest or water",
        "within three spaces of a green structure",
        "within one space of swamp",
        "within two spaces of a standing stone",
        "not on water or swamp",
        "not on desert or mountain",
        "on swamp or mountain",
        "within one space of mountain",
        "not within two spaces of cougar territory",
        "not on desert or water",
        "on forest or water",
        "on swamp or mountain",
        "not on water or swamp",
        "not on forest or mountain",
        "within three spaces of a blue structure",
        "within one space of forest",
        "not within three spaces of a white structure",
        "on water or mountains",
        "on desert or mountain",
        "not on desert or water",
        "not on desert or swamp",
        "on forest or swamp",
        "not within one space of mountain",
        "within three spaces of a blue structure",
        "on forest or mountain",
        "within three spaces of a white structure",
        "not within one space of swamp",
        "not on swamp or mountain",
        "on desert or swamp",
        "not within two spaces of bear territory",
        "within one space of swamp",
        "not within one space of water",
        "not within two spaces of an abandoned shack",
        "not within two spaces of a standing stone",
        "within two spaces of an abandoned shack",
        "on desert or mountain",
        "not within three spaces of a white structure",
        "not within one space of water",
        "not within three spaces of a green structure",
        "on water or swamp",
        "within one space of desert",
        "within one space of mountain",
        "not on swamp or mountain",
        "not within three spaces of a black structure",
        "not on forest or water",
        "on forest or desert",
        "not within three spaces of a black structure",
        "not within three spaces of a green structure",
        "not within three spaces of a blue structure",
        "on desert or swamp",
        "not on forest or swamp",
        "on desert or water",
        "not within one space of swamp",
        "not on water or mountains",
        "not within one space of forest",
        "within two spaces of an abandoned shack",
        "within two spaces of a standing stone",
        "on water or mountains",
        "not within two spaces of cougar territory",
        "within two spaces of bear territory",
        "on forest or desert",
        "not on water or mountains",
        "within two spaces of bear territory",
        "not on desert or mountain",
        "not within one space of forest",
        "within one space of either animal territory",
        "not on forest or water",
        "not within two spaces of a standing stone",
        "on water or swamp",
        "not within one space of desert",
    ],
}

def normalize(s: str) -> str:
	return " ".join(s.lower().split())

# Canonical rules 1–48
CANONICAL = [
	"not on desert or mountain",
	"not on desert or swamp",
	"not on desert or water",
	"not on forest or desert",
	"not on forest or mountain",
	"not on forest or swamp",
	"not on forest or water",
	"not on swamp or mountain",
	"not on water or mountains",
	"not on water or swamp",
	"not within one space of desert",
	"not within one space of either animal territory",
	"not within one space of forest",
	"not within one space of mountain",
	"not within one space of swamp",
	"not within one space of water",
	"not within three spaces of a black structure",
	"not within three spaces of a blue structure",
	"not within three spaces of a green structure",
	"not within three spaces of a white structure",
	"not within two spaces of a standing stone",
	"not within two spaces of an abandoned shack",
	"not within two spaces of bear territory",
	"not within two spaces of cougar territory",
	"on desert or mountain",
	"on desert or swamp",
	"on desert or water",
	"on forest or desert",
	"on forest or mountain",
	"on forest or swamp",
	"on forest or water",
	"on swamp or mountain",
	"on water or mountains",
	"on water or swamp",
	"within one space of desert",
	"within one space of either animal territory",
	"within one space of forest",
	"within one space of mountain",
	"within one space of swamp",
	"within one space of water",
	"within three spaces of a black structure",
	"within three spaces of a blue structure",
	"within three spaces of a green structure",
	"within three spaces of a white structure",
	"within two spaces of a standing stone",
	"within two spaces of an abandoned shack",
	"within two spaces of bear territory",
	"within two spaces of cougar territory",
]

# Map normalized clue text -> canonical number
canon_map = {normalize(txt): i+1 for i, txt in enumerate(CANONICAL)}

# Build numeric cluebooks
NUMERIC = {}
for book, clues in CLUEBOOKS.items():
	arr = []
	for clue in clues:
		n = normalize(clue)
		if n not in canon_map:
			raise ValueError(f"Clue not in canonical list: {clue}")
		arr.append(canon_map[n])
	NUMERIC[book] = arr

for book, arr in NUMERIC.items():
	print(book, arr)

def clue_text(book: str, index: int) -> str:
	"""book is one of A_Red, B_Green, C_Blue, D_Yellow, E_Purple; index is 1..96"""
	num = NUMERIC[book][index-1]  # convert 1-based index to list index
	return CANONICAL[num-1]

print ()
print("green, 62 ->", clue_text("B_Green", 62))
print("blue, 1   ->", clue_text("C_Blue", 1))
print("orange, 78 ->", clue_text("D_Orange", 78))      # "orange" is actually Red
print("purple, 65 ->", clue_text("E_Purple", 65))
